name: Mirror to shenapex/QQDecrypt

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  mirror:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: QQBackup/QQDecrypt
          token: ${{ secrets.GH_TOKEN }}  
          path: source

      - name: Configure Git
        run: |
          git config --global user.name "QQbackup"
          git config --global user.email "172821606+shenapex@users.noreply.github.com"

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd source
          git remote add target https://shenapex:${GH_TOKEN}@github.com/shenapex/QQDecrypt.git
          git push target main --force
