name: Mirror to weasUXL/QQDecrypt

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: QQBackup/QQDecrypt
          token: ${{ secrets.GH_TOKEN }}  
          path: source

      - name: Configure Git
        run: |
          git config --global user.name "QQbackup"
          git config --global user.email "issues@sbcnm.top"

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd source
          git remote add target https://weasUXL:${GH_TOKEN}@github.com/weasUXL/QQDecrypt.git
          git push target main --force
